"use client";
import {useState,useEffect,useRef,useCallback} from 'react';
import {BookOpen,FileText,ArrowUpRight,ChevronDown,Settings,Plus,Minus,Check} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {DropdownMenu,DropdownMenuTrigger,DropdownMenuContent,DropdownMenuItem} from '@/components/ui/dropdown-menu';
import {initial,progress,streak,today,EMOJIS,BOOKS,CHAPTERS,type Garden,type Reward,type Log} from '@/lib/garden';
import {mutateGarden,watchGarden,saveInvitation,watchInvitations} from '@/lib/firebase-garden';
const SAMPLE=['🌱','🌷','⛵','🐈','🪐','🌼','🦋','🌳','🍞','🍀','🎸','🌻','🐢','🌈','🐇','☕'];
export default function GardenApp({uid,email,isOwner,onSignOut}:{uid:string;email:string;isOwner:boolean;onSignOut:()=>void}){
const [g,setG]=useState<Garden>(initial),[loaded,setLoaded]=useState(false),[error,setError]=useState(''),[page,setPage]=useState('garden'),[busy,setBusy]=useState(false),[toast,setToast]=useState('');
const [modal,setModal]=useState(''),[bible,setBible]=useState(0),[life,setLife]=useState(0),[date,setDate]=useState(today),[note,setNote]=useState(''),[name,setName]=useState(''),[book,setBook]=useState('約翰福音'),[lifeBook,setLifeBook]=useState('約翰福音'),[targetB,setTargetB]=useState(6),[targetL,setTargetL]=useState(16),[stepB,setStepB]=useState(3),[stepL,setStepL]=useState(3),[editing,setEditing]=useState<Log|null>(null),[choosing,setChoosing]=useState<Reward|null>(null);
const [selected,setSelected]=useState<Reward|null>(null),[placing,setPlacing]=useState<Reward|null>(null),[candidate,setCandidate]=useState<{x:number;y:number}|null>(null),[view,setView]=useState({x:0,y:0,z:1}),[dimensions,setDimensions]=useState({w:1000,h:650});
const canvas=useRef<HTMLDivElement>(null),drag=useRef<{x:number;y:number;vx:number;vy:number;moved:boolean}|null>(null),lastPage=useRef('garden');
const me=g.members.find(m=>m.id===uid)??{id:uid,name:email.split('@')[0],baseBible:0,baseLife:0};const p=progress(g,me.id),combo=streak(g,me.id),cycle=combo?((combo-1)%7)+1:0;const mine=g.rewards.filter(r=>r.member===me.id),collection=mine.filter(r=>r.x===null),ownLogs=g.logs.filter(l=>l.member===me.id).sort((a,b)=>b.date.localeCompare(a.date));
const notify=useCallback((s:string)=>{setToast(s);setTimeout(()=>setToast(''),4500)},[]);
useEffect(()=>watchGarden(x=>{setG(x);setLoaded(true);setError('')},e=>setError(e.message)),[]);
useEffect(()=>{if(lastPage.current!==page){window.scrollTo({top:0});lastPage.current=page}if(page==='garden'&&canvas.current){const observer=new ResizeObserver(entries=>{const r=entries[0].contentRect;setDimensions({w:r.width,h:r.height})});observer.observe(canvas.current);return()=>observer.disconnect()}},[page]);

async function mutate(action:string,data:Record<string,unknown>={}){setBusy(true);try{const result=await mutateGarden(uid,g,action,data);setError('');return {...g,rewards:[...g.rewards,...Array.from({length:result.gained},(_,i)=>({id:'pending-'+i,member:uid,emoji:'🎁',source:'',date:today(),x:null,y:null}))]} as Garden}catch(e){notify(e instanceof Error?e.message:'儲存失敗，請重試');return null}finally{setBusy(false)}}
function openRecord(){setBible(p.bible);setLife(p.life);setDate(today());setNote('');setModal('record')}
function openProfile(){setName(me.name);setBible(me.baseBible);setLife(me.baseLife);setModal('profile')}
function openPlan(){setBook(g.plan.book);setLifeBook(g.plan.lifeBook);setTargetB(g.plan.bibleTarget);setTargetL(g.plan.lifeTarget);setStepB(g.plan.bibleStep);setStepL(g.plan.lifeStep);setModal('plan')}
async function saveRecord(){const count=g.rewards.length;const next=await mutate('record',{bible,life,date,note,requestId:crypto.randomUUID()});if(next){setModal('');const gained=next.rewards.length-count;notify(gained?`閱讀已記錄！得到 ${gained} 個新獎勵。`:'閱讀已記錄，繼續慢慢累積。')}}
function beginPlace(r:Reward){setPlacing(r);setSelected(null);setCandidate(null);setPage('garden');window.scrollTo({top:0});notify('點一下喜歡的位置，或拖曳畫布尋找空位。')}
function pos(x:number,y:number){return {left:dimensions.w/2+(x-view.x)*view.z,top:dimensions.h/2+(y-view.y)*view.z}}
function screenToWorld(x:number,y:number){const rect=canvas.current!.getBoundingClientRect();return {x:view.x+(x-rect.left-dimensions.w/2)/view.z,y:view.y+(y-rect.top-dimensions.h/2)/view.z}}
const navigate=(s:string)=>{setPage(s);setSelected(null)};

const modalTitles:Record<string,string>={accounts:'同伴帳號管理',record:'記錄今天的閱讀',profile:'我的起始位置',plan:'共同計畫設定',choose:'選一個喜歡的 emoji',edit:'編輯閱讀紀錄'};
return <><header><button className="brand brand-button" onClick={()=>navigate('garden')}>共讀花園 <span>🌱</span></button><nav><button className={page==='garden'?'active':''} onClick={()=>navigate('garden')}>共同空間</button><button className={page==='personal'?'active':''} onClick={()=>navigate('personal')}>我的進度</button></nav><DropdownMenu><DropdownMenuTrigger asChild><button className="profile-button"><span className="avatar">{me.name.slice(0,1)}</span><span className="profile-name">{me.name}</span><ChevronDown size={14}/></button></DropdownMenuTrigger><DropdownMenuContent className="rounded-3xl p-2 bg-[#edf0e9]"><DropdownMenuItem className="rounded-full p-3" onClick={()=>navigate('personal')}>我的進度</DropdownMenuItem>{isOwner&&<DropdownMenuItem className="rounded-full p-3" onClick={()=>setModal('accounts')}>帳號管理</DropdownMenuItem>}<DropdownMenuItem className="rounded-full p-3" onClick={onSignOut}>登出</DropdownMenuItem></DropdownMenuContent></DropdownMenu></header>
{page==='garden'?<><div ref={canvas} className={'canvas'+(placing?' placing-mode':'')} aria-label="可拖曳及縮放的共同成就空間" onPointerDown={e=>{if(e.target!==e.currentTarget)return;drag.current={x:e.clientX,y:e.clientY,vx:view.x,vy:view.y,moved:false};e.currentTarget.setPointerCapture(e.pointerId)}} onPointerMove={e=>{const d=drag.current;if(!d)return;const dx=e.clientX-d.x,dy=e.clientY-d.y;if(Math.hypot(dx,dy)>5)d.moved=true;if(d.moved)setView(v=>({...v,x:d.vx-dx/v.z,y:d.vy-dy/v.z}))}} onPointerUp={e=>{const d=drag.current;drag.current=null;if(d&&!d.moved){if(placing)setCandidate(screenToWorld(e.clientX,e.clientY));else setSelected(null)}}} onPointerCancel={()=>{drag.current=null}} onWheel={e=>{if(!e.ctrlKey)return;setView(v=>({...v,z:Math.max(.3,Math.min(2.5,v.z*(e.deltaY>0?.94:1.06)))}))}}>
{placing&&<div className="placing" onPointerDown={e=>e.stopPropagation()}><span>{placing.emoji} 選擇一個空位</span><button className="mini" onClick={()=>{setPlacing(null);setCandidate(null)}}>取消</button></div>}
{!g.rewards.some(r=>r.x!==null)&&SAMPLE.map((emoji,i)=><button key={'sample'+i} className="emoji sample-emoji" style={pos(((i*173)%750)-375,((i*113)%480)-240)} aria-label={`${emoji} 示意成果`} onPointerDown={e=>e.stopPropagation()} onClick={()=>placing?setCandidate({x:((i*173)%750)-375,y:((i*113)%480)-240}):notify('這些是示意 emoji，第一次放下成就後會換成大家的成果。')}>{emoji}</button>)}
{g.rewards.filter(r=>r.x!==null&&r.y!==null).filter(r=>{const sp=pos(r.x!,r.y!);return sp.left>-80&&sp.left<dimensions.w+80&&sp.top>-80&&sp.top<dimensions.h+80}).map(r=><button key={r.id} className="emoji" style={{...pos(r.x!,r.y!),fontSize:Math.max(22,36*view.z)}} aria-label={`${g.members.find(m=>m.id===r.member)?.name}的${r.emoji}，${r.source}`} onPointerDown={e=>e.stopPropagation()} onClick={()=>{if(!placing)setSelected(r)}}>{r.emoji}</button>)}
{candidate&&placing&&<div className="candidate" style={pos(candidate.x,candidate.y)} onPointerDown={e=>e.stopPropagation()}><span>{placing.emoji}</span><button disabled={busy} className="primary" onClick={async()=>{const next=await mutate('place',{id:placing.id,...candidate});if(next){setPlacing(null);setCandidate(null);notify('已放進我們的共同空間。')}}}>放在這裡 <Check size={14}/></button></div>}
{selected&&!placing&&<div className="tip" onPointerDown={e=>e.stopPropagation()}><div className="row"><span className="tip-emoji">{selected.emoji}</span><button className="mini" aria-label="關閉成就資訊" onClick={()=>setSelected(null)}>×</button></div><h2>{g.members.find(m=>m.id===selected.member)?.name}的閱讀成就</h2><p className="muted">{selected.source}<br/>{selected.date}</p>{selected.member===me.id&&<div className="row"><button className="outline" onClick={()=>beginPlace(selected)}>移動</button><button className="outline" disabled={busy} onClick={async()=>{if(await mutate('collect',{id:selected.id})){setSelected(null);notify('已收回收藏。')}}}>收回收藏</button></div>}</div>}
<div className="canvas-controls" onPointerDown={e=>e.stopPropagation()}><button aria-label="縮小畫布" onClick={()=>setView(v=>({...v,z:Math.max(.3,v.z-.15)}))}><Minus size={16}/></button><button aria-label="放大畫布" onClick={()=>setView(v=>({...v,z:Math.min(2.5,v.z+.15)}))}><Plus size={16}/></button><button onClick={()=>setView({x:0,y:0,z:1})}>回到中心</button></div><a className="scroll-hint" href="#companions">往下看看我們的旅程 ↓</a></div>
<section id="companions" className="below"><div className="row"><div><p className="eyebrow">TOGETHER, LITTLE BY LITTLE</p><h1>一起栽培的同伴</h1></div><span className="muted">{g.members.length} 位同伴 · {g.rewards.filter(r=>r.x!==null).length} 個共同足跡</span></div><div className="members">{g.members.map((m,i)=><button key={m.id} className={'member '+(m.id===me.id?'selected':'')} onClick={()=>{if(m.id===uid)navigate('personal');else notify(`${m.name}目前讀到聖經第 ${progress(g,m.id).bible} 章、生命讀經第 ${progress(g,m.id).life} 篇。`)}}><span className={'avatar tone-'+i}>{m.name.slice(0,1)}</span>{m.name}{m.id===me.id&&<span className="badge">我</span>}</button>)}</div><div className="section grid"><div className="card"><div className="row"><h2>今日共同進度</h2>{isOwner&&<button className="icon-button" aria-label="設定共同計畫" onClick={openPlan}><Settings size={18}/></button>}</div><p>{g.plan.book} 第 {g.plan.bibleTarget} 章</p><p className="muted">{g.plan.lifeBook}生命讀經 第 {g.plan.lifeTarget} 篇</p></div><div className="card"><h2>{me.name}的閱讀旅程</h2><p className="muted">聖經 第 {p.bible} 章 · 生命讀經 第 {p.life} 篇</p><button className="primary" onClick={()=>navigate('personal')}>管理我的進度 <ArrowUpRight size={17}/></button></div></div><p className="preview-note">名字、共同進度與獎勵門檻目前為示例，可在個人頁與共同計畫中修改。{!g.rewards.some(r=>r.x!==null)&&' 畫布目前展示示意 emoji。'}</p>{error&&<div role="alert" className="error-card">{error}<button className="outline" onClick={()=>window.location.reload()}>重新載入</button></div>}</section></>:<main className="personal"><div className="row"><div><p className="eyebrow">MY READING JOURNEY</p><h1>我的閱讀旅程</h1><p className="muted">{me.name} · 一步一步，累積自己的追求。</p></div><button className="outline" onClick={openProfile}><Settings size={16}/> 個人設定</button></div>{error&&<div role="alert" className="error-card">{error}<button className="outline" onClick={()=>window.location.reload()}>重新載入</button></div>}
<div className="grid progress-grid"><div className="card progress-card"><div className="reading-icon"><BookOpen size={26}/></div><div><p className="muted">聖經</p><h3>{g.plan.book} 第 {p.bible} 章</h3><p className="muted">{p.bible<CHAPTERS[BOOKS.indexOf(g.plan.book)]?`接下來：第 ${p.bible+1} 章`:'這卷聖經已讀完'}</p></div></div><div className="card progress-card"><div className="reading-icon"><FileText size={26}/></div><div><p className="muted">生命讀經</p><h3>{g.plan.lifeBook} 第 {p.life} 篇</h3><p className="muted">接下來：第 {p.life+1} 篇</p></div></div></div><div className="record-cta"><button className="primary" disabled={!loaded||busy} onClick={openRecord}><Plus size={18}/> 記錄閱讀</button></div>
<section className="section"><div className="row"><h2>今日共同進度</h2>{isOwner&&<button className="text-button" onClick={openPlan}>調整計畫</button>}</div><p className="muted">聖經：第 {g.plan.bibleTarget} 章　生命讀經：第 {g.plan.lifeTarget} 篇</p><p className="muted">{p.bible>=g.plan.bibleTarget&&p.life>=g.plan.lifeTarget?'已跟上目前共同進度 🌱':`待補：${Math.max(0,g.plan.bibleTarget-p.bible)} 章・${Math.max(0,g.plan.lifeTarget-p.life)} 篇`}</p></section>
<section className="section"><div className="card combo-card"><div><h2>連續閱讀 {combo} 天</h2><p className="muted">聖經或生命讀經有閱讀，都算一天。</p></div><div><div className="dots" aria-label={`本輪已累積 ${cycle} 天，共 7 天`}>{Array.from({length:7},(_,i)=><span key={i} className={'dot '+(i<cycle?'filled':'')}/>)}</div><p className="muted">{cycle===7?'完成一週！自選獎勵已加入收藏。':`再讀 ${7-cycle} 天，就能自選 1 個 emoji。`}</p></div></div></section>
<section className="section"><div className="row"><div><h2>我的收藏 <span className="badge">{collection.length}</span></h2><p className="muted">尚未放置的閱讀成就</p></div><button className="outline" onClick={()=>navigate('garden')}>回到共同空間 <ArrowUpRight size={16}/></button></div><div className="collection">{collection.map(r=><button key={r.id} title={r.source} aria-label={r.emoji?`放置 ${r.emoji}，${r.source}`:'選擇連續閱讀獎勵'} onClick={()=>{if(r.emoji)beginPlace(r);else{setChoosing(r);setModal('choose')}}}>{r.emoji??'🎁'}{!r.emoji&&<span className="reward-label">自選</span>}</button>)}</div>{!collection.length&&<p className="empty">完成閱讀後，新的 emoji 會在這裡等你。</p>}<p className="muted">每累積 {g.plan.bibleStep} 章聖經或 {g.plan.lifeStep} 篇生命讀經，隨機得到 1 個 emoji。</p><div className="reward-progress"><span>聖經：{p.bibleRead%g.plan.bibleStep}／{g.plan.bibleStep} 章</span><span>生命讀經：{p.lifeRead%g.plan.lifeStep}／{g.plan.lifeStep} 篇</span></div><div className="milestone"><span>⚑</span> 里程碑獎勵 · 待規劃</div></section>
<section className="section"><h2>閱讀紀錄 <span className="badge">{ownLogs.length}</span></h2>{ownLogs.length?ownLogs.map(l=><div className="history row" key={l.id}><div><span className="date-label">{l.date}</span><span>{[l.bible?`${g.plan.book} ${l.bible} 章`:'',l.life?`生命讀經 ${l.life} 篇`:''].filter(Boolean).join(' · ')}</span>{l.note&&<p className="muted history-note">{l.note}</p>}</div><button className="text-button" onClick={()=>{setEditing(l);setBible(l.bible);setLife(l.life);setNote(l.note);setModal('edit')}}>編輯</button></div>):<p className="empty">還沒有閱讀紀錄。先設定起始位置，再記錄這次的閱讀。</p>}</section>
</main>}
<Dialog open={!!modal} onOpenChange={v=>{if(!v&&!busy)setModal('')}}><DialogContent className="modal max-h-[88svh] overflow-y-auto"><DialogTitle>{modalTitles[modal]??'閱讀記錄'}</DialogTitle><DialogDescription>{modal==='record'?'填入這次讀完的位置，我們會接續上次的進度。':modal==='profile'?'先選好自己的名字與開始使用網站前讀到的位置。':modal==='plan'?'設定目前的共讀書卷、今日目標與閱讀獎勵門檻。':modal==='choose'?'連續讀滿一週，這次由你決定。':'查看與修正自己的閱讀紀錄。'}</DialogDescription>
{(modal==='record'||modal==='profile'||modal==='edit')&&<form onSubmit={e=>{e.preventDefault();if(modal==='record')saveRecord();else mutate(modal==='profile'?'profile':'edit',{name,bible,life,note,id:editing?.id}).then(next=>{if(next){setModal('');notify('已儲存。')}})}}>
{modal==='profile'&&<label>我的名字<input value={name} maxLength={12} required onChange={e=>setName(e.target.value)}/></label>}
{modal==='record'&&<label>實際閱讀日期<input type="date" value={date} max={today()} required onChange={e=>setDate(e.target.value)}/></label>}
<div className="form-grid"><label>{modal==='edit'?'這次讀了幾章':`${g.plan.book}讀完到第幾章`}<input type="number" value={bible} min={modal==='record'?p.bible:0} max={CHAPTERS[BOOKS.indexOf(g.plan.book)]} required disabled={modal==='profile'&&ownLogs.length>0||modal==='edit'} onChange={e=>setBible(Number(e.target.value))}/></label><label>{modal==='edit'?'這次讀了幾篇':`${g.plan.lifeBook}生命讀經讀完到第幾篇`}<input type="number" value={life} min={modal==='record'?p.life:0} max={10000} required disabled={modal==='profile'&&ownLogs.length>0||modal==='edit'} onChange={e=>setLife(Number(e.target.value))}/></label></div>
{modal!=='profile'&&<label>一點摸著（選填）<textarea value={note} maxLength={1000} rows={3} onChange={e=>setNote(e.target.value)}/></label>}
{modal==='profile'&&<p className="muted">起始位置不發放獎勵；新增的閱讀才會累積。{ownLogs.length>0&&' 已有閱讀紀錄，起始位置已固定。'}</p>}{modal==='edit'&&<p className="muted">為了讓進度與已發出的成就一致，閱讀數量會保留；你可以修改這筆心得。</p>}
<button className="primary full" disabled={busy||!loaded} type="submit">{busy?'儲存中…':'儲存紀錄'}</button></form>}
{modal==='plan'&&<form onSubmit={e=>{e.preventDefault();mutate('plan',{book,lifeBook,bibleTarget:targetB,lifeTarget:targetL,bibleStep:stepB,lifeStep:stepL}).then(next=>{if(next){setModal('');notify('共同計畫已更新。')}})}}><label>共讀聖經書卷<Select value={book} onValueChange={v=>{setBook(v);setTargetB(Math.min(targetB,CHAPTERS[BOOKS.indexOf(v)]))}}><SelectTrigger className="w-full rounded-full mt-2 h-12"><SelectValue/></SelectTrigger><SelectContent className="rounded-3xl">{BOOKS.map(b=><SelectItem key={b} value={b}>{b}</SelectItem>)}</SelectContent></Select></label><label>生命讀經名稱<input value={lifeBook} required maxLength={40} onChange={e=>setLifeBook(e.target.value)}/></label><div className="form-grid"><label>今日聖經目標（章）<input type="number" min={0} max={CHAPTERS[BOOKS.indexOf(book)]} value={targetB} onChange={e=>setTargetB(Number(e.target.value))}/></label><label>今日生命讀經目標（篇）<input type="number" min={0} max={10000} value={targetL} onChange={e=>setTargetL(Number(e.target.value))}/></label><label>每幾章獲得 emoji<input type="number" min={1} max={100} value={stepB} disabled={g.rewards.length>0} onChange={e=>setStepB(Number(e.target.value))}/></label><label>每幾篇獲得 emoji<input type="number" min={1} max={100} value={stepL} disabled={g.rewards.length>0} onChange={e=>setStepL(Number(e.target.value))}/></label></div><p className="muted">已有閱讀紀錄後，這一輪的書卷固定；今日目標仍可調整。下一卷的切換流程待後續設定。</p><button className="primary full" disabled={busy||!loaded}>{busy?'儲存中…':'儲存共同計畫'}</button></form>}
{modal==='accounts'&&isOwner&&<AccountManager notify={notify}/>}
{modal==='choose'&&<div className="emoji-picker">{EMOJIS.map(emoji=><button key={emoji} disabled={busy} aria-label={`選擇 ${emoji}`} onClick={async()=>{if(choosing&&await mutate('choose',{id:choosing.id,emoji})){setModal('');notify(`${emoji} 已加入你的收藏。`)}}}>{emoji}</button>)}</div>}
</DialogContent></Dialog>{toast&&<div className="toast" role="status">{toast}</div>}</>
}

function AccountManager({notify}:{notify:(s:string)=>void}){const [rows,setRows]=useState<import('@/lib/firebase-garden').Invitation[]>([]),[email,setEmail]=useState(''),[name,setName]=useState(''),[saving,setSaving]=useState(false);useEffect(()=>watchInvitations(setRows,e=>notify(e.message)),[notify]);return <div><p className="muted">輸入同伴的 Gmail。對方登入後會固定綁定自己的閱讀身分。</p><form onSubmit={async e=>{e.preventDefault();setSaving(true);try{await saveInvitation(email,name);setEmail('');setName('');notify('已儲存同伴帳號。')}catch(err){notify(err instanceof Error?err.message:'儲存失敗')}finally{setSaving(false)}}}><label>同伴名字<input value={name} maxLength={12} required onChange={e=>setName(e.target.value)}/></label><label>Google 帳號<input type="email" value={email} required onChange={e=>setEmail(e.target.value)} placeholder="friend@gmail.com"/></label><button className="primary full" disabled={saving}>{saving?'儲存中…':'儲存帳號綁定'}</button></form><div className="invite-list">{rows.map(r=><div className="history" key={r.id}><strong>{r.name}</strong><span className="muted">{r.email} · {r.claimedUid?'已加入':'等待加入'}</span></div>)}</div></div>}
