export const EMOJIS=['🌱','🌷','🌼','🌻','🌿','🍀','🌳','🦋','🐈','🐕','🐢','🐇','🐳','🦊','🐧','⛵','🪐','⭐','🌙','☀️','🌈','🍞','🍎','🍓','🍉','🍕','☕','🎸','🎨','🎈','🏡','🚲','🧸','📚','🕊️','💛'];
export const BOOKS=['創世記','出埃及記','利未記','民數記','申命記','約書亞記','士師記','路得記','撒母耳記上','撒母耳記下','列王紀上','列王紀下','歷代志上','歷代志下','以斯拉記','尼希米記','以斯帖記','約伯記','詩篇','箴言','傳道書','雅歌','以賽亞書','耶利米書','耶利米哀歌','以西結書','但以理書','何西阿書','約珥書','阿摩司書','俄巴底亞書','約拿書','彌迦書','那鴻書','哈巴谷書','西番雅書','哈該書','撒迦利亞書','瑪拉基書','馬太福音','馬可福音','路加福音','約翰福音','使徒行傳','羅馬書','哥林多前書','哥林多後書','加拉太書','以弗所書','腓立比書','歌羅西書','帖撒羅尼迦前書','帖撒羅尼迦後書','提摩太前書','提摩太後書','提多書','腓利門書','希伯來書','雅各書','彼得前書','彼得後書','約翰一書','約翰二書','約翰三書','猶大書','啟示錄'];
export const CHAPTERS=[50,40,27,36,34,24,21,4,31,24,22,25,29,36,10,13,10,42,150,31,12,8,66,52,5,48,12,14,3,9,1,4,7,3,3,3,2,14,4,28,16,24,21,28,16,16,13,6,6,4,4,5,3,6,4,3,1,13,5,5,3,5,1,1,1,22];
export type Member={id:string;name:string;baseBible:number;baseLife:number};
export type Log={id:string;member:string;date:string;bible:number;life:number;note:string};
export type Reward={id:string;member:string;emoji:string|null;source:string;date:string;x:number|null;y:number|null};
export type Garden={members:Member[];logs:Log[];rewards:Reward[];plan:{book:string;lifeBook:string;bibleTarget:number;lifeTarget:number;bibleStep:number;lifeStep:number}};
export function today(){return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Taipei',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}
export function shiftDate(s:string,n:number){return new Date(Date.parse(s+'T12:00:00Z')+n*86400000).toISOString().slice(0,10)}
export function initial():Garden{return {members:['恩恩','小安','佳佳','以樂','晨晨','小禾'].map((name,i)=>({id:String(i+1),name,baseBible:0,baseLife:0})),logs:[],rewards:[],plan:{book:'約翰福音',lifeBook:'約翰福音',bibleTarget:6,lifeTarget:16,bibleStep:3,lifeStep:3}}}
export function progress(g:Garden,id:string){const m=g.members.find(m=>m.id===id)!;const ls=g.logs.filter(l=>l.member===id);return {bible:m.baseBible+ls.reduce((s,l)=>s+l.bible,0),life:m.baseLife+ls.reduce((s,l)=>s+l.life,0),bibleRead:ls.reduce((s,l)=>s+l.bible,0),lifeRead:ls.reduce((s,l)=>s+l.life,0)}}
export function streak(g:Garden,id:string){const dates=new Set(g.logs.filter(l=>l.member===id).map(l=>l.date));let end=today();if(!dates.has(end))end=shiftDate(end,-1);let days=0;while(dates.has(shiftDate(end,-days)))days++;return days}
export function grant(g:Garden,id:string){const p=progress(g,id);for(const [kind,count,step] of [['聖經',p.bibleRead,g.plan.bibleStep],['生命讀經',p.lifeRead,g.plan.lifeStep]] as [string,number,number][]){for(let i=1;i<=Math.floor(count/step);i++){const rid=`${id}-${kind}-${i}`;if(!g.rewards.some(r=>r.id===rid))g.rewards.push({id:rid,member:id,emoji:EMOJIS[Math.floor(Math.random()*EMOJIS.length)],source:`${kind}累積閱讀 ${i*step} ${kind==='聖經'?'章':'篇'}`,date:today(),x:null,y:null})}}
const dates=[...new Set(g.logs.filter(l=>l.member===id).map(l=>l.date))].sort();let run=0,earned=0;for(let i=0;i<dates.length;i++){run=i>0&&shiftDate(dates[i-1],1)===dates[i]?run+1:1;if(run%7===0){const rid=`${id}-combo-${++earned}`;if(!g.rewards.some(r=>r.id===rid))g.rewards.push({id:rid,member:id,emoji:null,source:'連續閱讀 7 天 · 自選獎勵',date:dates[i],x:null,y:null})}}}
