import {z} from 'zod';
import {env} from 'cloudflare:workers';
import {initial,progress,grant,today,EMOJIS,BOOKS,CHAPTERS,type Garden} from '@/lib/garden';
function db(){if(!env.DB)throw new Error('共享儲存暫時無法使用');return env.DB}
async function read(){const d=db();await d.prepare('INSERT OR IGNORE INTO gardens(id,data,revision) VALUES(?,?,0)').bind('shared',JSON.stringify(initial())).run();const row=await d.prepare('SELECT data,revision FROM gardens WHERE id=?').bind('shared').first<{data:string;revision:number}>();if(!row)throw new Error('無法讀取花園');return {garden:JSON.parse(row.data) as Garden,revision:row.revision}}
export async function GET(){try{return Response.json(await read(),{headers:{'Cache-Control':'no-store'}})}catch(e){console.error(e);return Response.json({error:'花園暫時無法載入，請稍後再試。'},{status:503})}}
const int=(v:unknown,min=0,max=10000)=>{if(typeof v!=='number'||!Number.isInteger(v)||v<min||v>max)throw new Error('請輸入有效的數字');return v};
export async function POST(req:Request){try{const body=z.object({action:z.enum(['record','place','collect','choose','profile','plan','edit']),revision:z.number().int().nonnegative(),member:z.string(),bible:z.number().optional(),life:z.number().optional(),date:z.string().default(''),note:z.string().default(''),requestId:z.string().default(''),id:z.string().default(''),emoji:z.string().default(''),x:z.number().default(0),y:z.number().default(0),name:z.string().default(''),book:z.string().default(''),lifeBook:z.string().default(''),bibleTarget:z.number().optional(),lifeTarget:z.number().optional(),bibleStep:z.number().optional(),lifeStep:z.number().optional()}).parse(await req.json());const {garden:g,revision}=await read();if(body.revision!==revision)return Response.json({error:'同伴剛更新了花園，請重新載入後再儲存。'},{status:409});const m=g.members.find(m=>m.id===body.member);if(!m)throw new Error('請選擇同伴');
if(body.action==='record'){const bible=int(body.bible,0,CHAPTERS[BOOKS.indexOf(g.plan.book)]),life=int(body.life);const p=progress(g,m.id);if(bible<p.bible||life<p.life)throw new Error('進度不能倒退；請在閱讀紀錄修正。');if(bible===p.bible&&life===p.life)throw new Error('這次還沒有新增閱讀進度');if(typeof body.date!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(body.date)||isNaN(Date.parse(body.date))||new Date(body.date+'T12:00:00Z').toISOString().slice(0,10)!==body.date||body.date>today())throw new Error('請選擇有效的閱讀日期');if(typeof body.requestId!=='string'||body.requestId.length>80)throw new Error('無效的記錄');if(g.logs.some(l=>l.id===body.requestId))return Response.json({garden:g,revision});g.logs.push({id:body.requestId,member:m.id,date:body.date,bible:bible-p.bible,life:life-p.life,note:String(body.note??'').slice(0,1000)});grant(g,m.id);
}else if(body.action==='place'||body.action==='collect'||body.action==='choose'){const r=g.rewards.find(r=>r.id===body.id&&r.member===m.id);if(!r)throw new Error('找不到自己的成就');if(body.action==='choose'){if(r.emoji!==null||!EMOJIS.includes(body.emoji))throw new Error('這個獎勵不能再選擇');r.emoji=body.emoji}else if(body.action==='collect'){r.x=null;r.y=null}else{if(!r.emoji)throw new Error('請先選擇 emoji');for(const v of [body.x,body.y])if(typeof v!=='number'||!Number.isFinite(v)||Math.abs(v)>10000000)throw new Error('位置超出範圍');if(g.rewards.some(v=>v.id!==r.id&&v.x!==null&&v.y!==null&&Math.hypot(v.x-body.x,v.y-body.y)<48))throw new Error('這裡離另一個成就太近了，請選一個空位');r.x=Math.round(body.x);r.y=Math.round(body.y)}}
else if(body.action==='profile'){const name=String(body.name??'').trim();if(!name||name.length>12)throw new Error('名字請使用 1～12 個字');m.name=name;if(!g.logs.some(l=>l.member===m.id)){m.baseBible=int(body.bible,0,CHAPTERS[BOOKS.indexOf(g.plan.book)]);m.baseLife=int(body.life)}else if(body.bible!==m.baseBible||body.life!==m.baseLife)throw new Error('已有紀錄，起始位置不能直接修改');}
else if(body.action==='plan'){if(!BOOKS.includes(body.book))throw new Error('請選擇書卷');if((body.book!==g.plan.book||body.lifeBook!==g.plan.lifeBook)&&g.logs.length)throw new Error('已有閱讀紀錄，目前不能更換共讀書卷');const bibleStep=int(body.bibleStep,1,100),lifeStep=int(body.lifeStep,1,100);if(g.rewards.length&&(bibleStep!==g.plan.bibleStep||lifeStep!==g.plan.lifeStep))throw new Error('已有獎勵，請保留目前的獎勵門檻');g.plan={book:body.book,lifeBook:String(body.lifeBook??body.book).slice(0,40),bibleTarget:int(body.bibleTarget,0,CHAPTERS[BOOKS.indexOf(body.book)]),lifeTarget:int(body.lifeTarget),bibleStep,lifeStep}}
else if(body.action==='edit'){const l=g.logs.find(l=>l.id===body.id&&l.member===m.id);if(!l)throw new Error('找不到閱讀紀錄');const oldB=l.bible,oldL=l.life;l.bible=int(body.bible,0,CHAPTERS[BOOKS.indexOf(g.plan.book)]);l.life=int(body.life);l.note=String(body.note??'').slice(0,1000);if(!l.bible&&!l.life)throw new Error('紀錄至少需要一章或一篇');if(progress(g,m.id).bible>CHAPTERS[BOOKS.indexOf(g.plan.book)])throw new Error('超出書卷的章數');if((l.bible!==oldB||l.life!==oldL)&&g.rewards.some(r=>r.member===m.id))throw new Error('已有成就獎勵，暫時只開放修改心得。');grant(g,m.id)}
else throw new Error('不支援的操作');
const result=await db().prepare('UPDATE gardens SET data=?,revision=revision+1 WHERE id=? AND revision=?').bind(JSON.stringify(g),'shared',revision).run();if(result.meta.changes!==1)return Response.json({error:'花園剛被更新了，請重新載入後再儲存。'},{status:409});return Response.json({garden:g,revision:revision+1});
}catch(e){console.error(e);return Response.json({error:e instanceof Error?e.message:'儲存失敗，請再試一次'},{status:400})}}
